// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamServer.Data;

#nullable disable

namespace TeamServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230608102205_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TeamServer.Models.Listeners.Listener", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BindHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BindPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Listeners");
                });
#pragma warning restore 612, 618
        }
    }
}
